using AuditedEntity.Core;
using AuditedEntity.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace AuditedEntity
{
	public class MyDBContext : DbContext
	{
		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlServer(@"Server=localhost;Database=AuditedEntities;Trusted_Connection=True;");
			base.OnConfiguring(optionsBuilder);
		}

		// TODO: replace with the real current user once authentication exists.
		private const long CurrentUserId = 1;

		private class PendingAudit
		{
			public AuditReport Report { get; set; }
			// Set only for added entries, whose key is generated by the database on save.
			public EntityEntry GeneratedKeyEntry { get; set; }
		}

		public override int SaveChanges(bool acceptAllChangesOnSuccess)
		{
			var pending = PrepareAudit();
			if (pending.Count == 0)
				return base.SaveChanges(acceptAllChangesOnSuccess);

			var tx = Database.CurrentTransaction == null ? Database.BeginTransaction() : null;
			try
			{
				int result = base.SaveChanges(acceptAllChangesOnSuccess);
				AddAuditReports(pending);
				base.SaveChanges(acceptAllChangesOnSuccess);
				tx?.Commit();
				return result;
			}
			finally
			{
				tx?.Dispose();
			}
		}

		public override async Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default(CancellationToken))
		{
			var pending = PrepareAudit();
			if (pending.Count == 0)
				return await base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);

			var tx = Database.CurrentTransaction == null ? await Database.BeginTransactionAsync(cancellationToken) : null;
			try
			{
				int result = await base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);
				AddAuditReports(pending);
				await base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);
				tx?.Commit();
				return result;
			}
			finally
			{
				tx?.Dispose();
			}
		}

		/// <summary>
		/// Stamps audit columns, applies soft deletes and collects the audit rows for this save.
		/// </summary>
		private List<PendingAudit> PrepareAudit()
		{
			ChangeTracker.DetectChanges();

			var pending = new List<PendingAudit>();
			var now = DateTime.Now;

			// ToList: soft deletes change entry states while we iterate.
			foreach (var entry in ChangeTracker.Entries().ToList())
			{
				if (entry.State != EntityState.Added && entry.State != EntityState.Modified && entry.State != EntityState.Deleted)
					continue;

				var audited = entry.Entity as IAuditedEntity;

				// Stamp new rows first so the audit captures the stamped values.
				if (entry.State == EntityState.Added && audited != null)
				{
					audited.AddedBy = CurrentUserId;
					audited.AddedDate = now;
				}

				if (audited != null)
					CollectAudit(entry, pending);

				if (entry.State == EntityState.Modified)
				{
					if (audited != null)
					{
						audited.UpdatedBy = CurrentUserId;
						audited.UpdateDate = now;
					}
				}
				else if (entry.State == EntityState.Deleted && entry.Entity is ISoftDelete softDelete)
				{
					// Turn the delete into an update that only touches the soft-delete columns.
					entry.State = EntityState.Unchanged;
					softDelete.IsDeleted = true;
					if (audited != null)
					{
						audited.DeletedBy = CurrentUserId;
						audited.DeletedDate = now;
					}
					entry.State = EntityState.Modified;
				}
			}

			return pending;
		}

		private static void CollectAudit(EntityEntry entry, List<PendingAudit> pending)
		{
			string entityName = entry.Entity.GetType().Name;
			string type = entry.State.ToString();
			bool added = entry.State == EntityState.Added;
			// Generated keys of added entries are unknown until after the save.
			string primaryKey = added ? null : GetPrimaryKey(entry);

			if (entry.State == EntityState.Deleted)
			{
				pending.Add(new PendingAudit
				{
					Report = new AuditReport { PrimaryKey = primaryKey, EntityName = entityName, Type = type }
				});
				return;
			}

			foreach (var prop in entry.Properties)
			{
				string newValue = prop.CurrentValue?.ToString();
				string oldValue = null;

				if (!added)
				{
					if (!prop.IsModified || Equals(prop.CurrentValue, prop.OriginalValue))
						continue;
					oldValue = prop.OriginalValue?.ToString();
				}

				pending.Add(new PendingAudit
				{
					GeneratedKeyEntry = added ? entry : null,
					Report = new AuditReport
					{
						PrimaryKey = primaryKey,
						EntityName = entityName,
						Type = type,
						Column = prop.Metadata.Name,
						OldValue = oldValue,
						NewValue = newValue
					}
				});
			}
		}

		private static string GetPrimaryKey(EntityEntry entry)
		{
			var key = entry.Metadata.FindPrimaryKey();
			if (key == null)
				return null;

			return string.Join(",", key.Properties.Select(p => entry.Property(p.Name).CurrentValue?.ToString()));
		}

		private void AddAuditReports(List<PendingAudit> pending)
		{
			foreach (var item in pending)
			{
				if (item.GeneratedKeyEntry != null)
					item.Report.PrimaryKey = GetPrimaryKey(item.GeneratedKeyEntry);
			}

			AuditReport.AddRange(pending.Select(x => x.Report));
		}

		public DbSet<TestEntity> TestEntity { get; set; }
		public DbSet<AuditReport> AuditReport { get; set; }
		public DbSet<TestEntity1> TestEntity1 { get; set; }
		public DbSet<TestEntityWithoutAudit> TestEntityWithoutAudit { get; set; }
	}
}
